layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/8fb8b0e9d61d266721825ce116060773ea2503c2/topics/swift/swift.png

  - name: Xcode
    web_url: https://github.com/topics/xcode
    image_url: https://raw.githubusercontent.com/github/explore/530398b5c9b0fd57127e2564bd664575f02f52e4/topics/xcode/xcode.png

  - name: Objective-C
    web_url: https://github.com/topics/objective-c
    image_url: https://raw.githubusercontent.com/github/explore/41a2f55bebabb0c5cd5babcbfb4f8a8487f9e39b/topics/objective-c/objective-c.png
