layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Rust
    web_url: https://github.com/topics/rust
  - name: Terminal
    web_url: https://github.com/topics/terminal
  - name: Command line tools
    web_url: https://github.com/topics/command-line-tools
  - name: Swift
    web_url: https://github.com/topics/Swift
  - name: Objective-C
    web_url: https://github.com/topics/objective-c
  - name: iOS
    web_url: https://github.com/topics/ios
